blog/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.posts_list, name='posts_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
   	url(r'^post/new/$', views.post_new, name='post_new'),
   	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
   	url(r'^remove/(?P<pk>[0-9]+)$', views.post_remove, name='post_remove'),
]

music/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views

app_name = 'music'

urlpatterns = [
    # /music/
    url(r'^$', views.IndexView.as_view(), name='index'),
    # /music/album.id
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    # /music/album.id/fav
   # url(r'^(?P<album_id>[0-9]+)/favorite/$', views.favorite, name='favorite'),
    url(r'^album/add/$', views.AlbumCreate.as_view(), name='album-add'),
    url(r'^album/(?P<pk>[0-9]+)/$', views.AlbumUpdate.as_view(), name='album-update'),
    url(r'^album/(?P<pk>[0-9]+)/delete/$', views.AlbumDelete.as_view(), name='album-delete'),
    url(r'^register/$', views.UserFormView.as_view(), name='register'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^peeps/', include('people.urls')),
    url(r'^workout/', include('workout.urls')),
    url(r'', include('blog.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^simplegram/', include('simplegram.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

music/models.py
from django.db import models
from django.core.urlresolvers import reverse


class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.FileField()

    def get_absolute_url(self):
        return reverse('music:detail', kwargs={'pk':self.pk})

    def __str__(self):
        return self.artist + '- ' + self.album_title


class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)  # jak usune album - poleci tez song ktory byl z nim powiazany
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.song_title

music/forms.py
from django.contrib.auth.models import User
from django import forms

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']

music/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.core.urlresolvers import reverse_lazy
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from django.views.generic import View
from .forms import UserForm
from .models import Album

class IndexView(generic.ListView):
    template_name = 'music/index.html'

    def get_queryset(self):
        return Album.objects.all()

class DetailView(generic.DetailView):
    model = Album
    template_name = 'music/detail.html'


class AlbumCreate(CreateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo' ]

class AlbumUpdate(UpdateView):
    model = Album
    fields = ['artist', 'album_title', 'genre', 'album_logo' ]

class AlbumDelete(DeleteView):
    model = Album
    success_url = reverse_lazy('music:index')

class UserFormView(View):
    form_class = UserForm
    template_name = 'music/registration_form.html'
    #display blank form
    def get(self, request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form':form})
    #process form data
    def post(self, request):
        form = self.form_class(request.POST)

        if form.is_valid():

            user = form.save(commit=False)
            #cleaned(normalized) data
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()

            #returns User obj if credentials are correct

            user = authenticate(username=username, password=password)
            if user is not None:

                if user.is_active:
                    login(request, user)
                    return redirect('music:index')

        return render(request, self.template_name, {'form': form})

music/templates/music/album_form.html
{%  extends 'music/base.html' %}
{% block title %} Add new Album {% endblock %}
{% block album_active %}active{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock %}

music/templates/music/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}Viberr{% endblock %}</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'music/style.css '%}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
    </div><div class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'music:index' %}">Viberr</a>
            </div>
     <!-- items for navbar-->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'music:index' %}">
                            <span class="glyphicon glyphicon-cd" aria-hidden="true"></span>&nbsp;Albums
                        </a>
                    </li>
                    <li class="">
                        <a href="#">
                            <span class="glyphicon glyphicon-music" aria-hidden="true"></span>&nbsp;Songs
                        </a>
                    </li>
                </ul>

                <form class="navbar-form navbar-left" role="search" method="get" action="#">
                   <div class="form-group">
                       <input type="text" class="form-control" name="q" value="">
                   </div>
                   <button type="submit" class="btn btn-default">Search</button>
                </form>

                <ul class="nav navbar-nav navbar-right">
                    <li class="">
                            <a href="{%  url 'music:album-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add album
                            </a>
                    </li>
                    <li class="">
                            <a href="#">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                            </a>
                    </li>
                </ul>

            </div>

        </div>
    </div>
    {% block body %}
    {% endblock %}

</body>
</html>

music/templates/music/detail.html
{% extends 'music/base.html' %}
{% block title %}Album detail{% endblock %}
{% block body %}
    <img src="{{ album.album_logo.url }}"/>
    <h1>{{ album.artist }}</h1>
    <h2>{{ album.album_title }}</h2>

    {% if error_message %}
        <p><strong>{{ error_message }}</strong></p>
    {% endif %}

    <form action="#" method="post">
        {% csrf_token %}
            {% for song in album.song_set.all %}
                <input type="radio" id="song{{ forloop.counter }}" name="song" value="{{ song.id }}" />
                <label for="song{{ forloop.counter }}">
                    {{ song.song_title }}
                    {% if song.is_favorite %}
                        <img id="fav" src="https://image.flaticon.com/icons/png/128/13/13587.png" />
                    {% endif %}
                </label><br />
            {% endfor %}
            <input type="submit" value="Favorite">
    </form>

{% endblock %}

music/templates/music/index.html
{% extends 'music/base.html' %}

{% block body %}

<h1>Here are all my albums</h1>
    {% if object_list %}

                <div class="container">
                    <div class="row">
                        {% for album in object_list %}
                        <div class="col-offset-1 col-sm-4 alb-det">
                            <img class="cover" src="{{ album.album_logo.url }}"/><br /><br />
                            <a href="{% url 'music:detail' album.id %}">{{ album.artist}}  - {{ album.album_title }}</a>
                            <form action="{% url 'music:album-delete' album.id %}" method="post" style="display: inline">
                                {% csrf_token %}
                                <input type="hidden" name="album_id" value="{{ album.id }}"/>
                                <button type="submit" class="btn btn-default btn-sm">
                                    <span class="glyphicon glyphicon-trash"></span>
                                </button>
                            </form>
                        </div>
                        {% endfor %}
                    </div>
                </div>

    {% else %}
        <h3>Unfortunately You don't have any albums or just your database is empty yet. </h3>
    {% endif %}
{% endblock %}

music/templates/music/registration_form.html
{%  extends 'music/base.html' %}
{% block title %} Register {% endblock %}
{% block album_active %}active{% endblock %}
{% block body %}
<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'music/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>
{% endblock %}