blog/urls.py
from django.conf.urls import url
from . import views



urlpatterns = [
    url(r'^$', views.posts_list, name='posts_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name='post_detail'),
   	url(r'^post/new/$', views.post_new, name='post_new'),
   	url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
   	url(r'^remove/(?P<pk>[0-9]+)$', views.post_remove, name='post_remove'),
]

mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^music/', include('music.urls')),
    url(r'^blog/', include('blog.urls')),
    url(r'^peeps/', include('people.urls')),
    url(r'^workout/', include('workout.urls')),
    url(r'', include('blog.urls')),
    url(r'^notes/', include('notes.urls')),
    url(r'^simplegram/', include('simplegram.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

simplegram/urls.py
from django.conf.urls import url
from . import views

app_name = 'simplegram'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^add/$', views.PhotoAdd.as_view(), name='photo-add'),
]

simplegram/models.py
from django.db import models
from django.utils import timezone
from django.core.urlresolvers import reverse

class Photo(models.Model):
    created_date = models.DateTimeField(default=timezone.now)
    photo_title = models.CharField(max_length=100)
    photo_pic = models.FileField()

    def get_absolute_url(self):
        return reverse('simplegram:index')

    def __str__(self):
        return self.photo_title

simplegram/views.py
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import View
from .models import Photo

class IndexView(generic.ListView):
    template_name = 'simplegram/index.html'

    def get_queryset(self):
        return Photo.objects.all().order_by('created_date').reverse()


class PhotoAdd(CreateView):
    model = Photo
    fields = ['photo_pic']

simplegram/templates/simplegram/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>HelloPhoto radipawelec</title>
    {% load staticfiles %}
    <link href="https://fonts.googleapis.com/css?family=Satisfy" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
    <link rel="stylesheet" type="text/css" href="{% static 'simplegram/style.css'%}" />
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>


<!-- menu -->
<div id="custom-bootstrap-menu" class="navbar navbar-default navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'simplegram:index' %}"><span class="glyphicon glyphicon-camera" aria-hidden="true"></span> | HelloPhoto</a>
            </div>
     <!-- items for navbar-->
            <div class="collapse navbar-collapse" id="topNavBar">

                <ul class="nav navbar-nav">
                    <li class="active">
                        <a href="{% url 'simplegram:index' %}">
                            <span class="glyphicon glyphicon-picture" aria-hidden="true"></span>&nbsp;Photos
                        </a>
                    </li>
                </ul>


                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li class="">
                            <a href="{% url 'simplegram:photo-add' %}">
                                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp;Add photo
                            </a>
                    </li>
                    <li class="">
                            <a href="../admin/logout/">
                                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp;Logout
                            </a>
                    </li>
                    {% else %}
                    <li class="">
                            <a href="../admin/">
                                <span class="glyphicon glyphicon-user" aria-hidden="true"></span>&nbsp;Zaloguj
                            </a>
                    </li>
                    {% endif %}
                </ul>

            </div>

        </div>
    </div>
<!-- menuend -->
<section class="main">
    {% block body %}
    {% endblock %}

</section>

</body>
</html>

simplegram/templates/simplegram/form-template.html
{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

simplegram/templates/simplegram/index.html
{% extends 'simplegram/base.html' %}

{% block body %}


    {% if object_list %}
    <div class="container">
        <div class="row">
            {% for photo in object_list %}
            <div class="col-sm-offset-4 col-sm-4 photo-frame">
                <img class="photo" src="{{ photo.photo_pic.url }}"/>
            </div>
            {% endfor %}
        </div>
    </div>
    {% else %}
        <h3>Unfortunately You don't have any albums or just your database is empty yet. </h3>
    {% endif %}




{% endblock %}

simplegram/templates/simplegram/photo_form.html
{% extends 'simplegram/base.html' %}

{% block body %}


<div class="container">
    <div class="row">
        <div class="panel panel-default">
            <div class="panel panel-body">

                <form class="form-horizontal" action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% include 'simplegram/form-template.html' %}
                    <div class="form-group">
                        <div class="col-sm-offset-2 col-sm-10">
                            <button type="submit" class="btn btn-success">Submit</button>
                        </div>
                    </div>

                </form>

            </div>
        </div>
    </div>

    {% endblock %}